[build]
  # This is the directory that contains the built files
  publish = "build"
  
  # This is the command to build your site
  command = "npm run build"

[build.environment]
  # Set Node.js version
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 